name: Check Ratchakitcha

on:
  schedule:
    - cron: '0 2 * * 2,4'  # 09:00 ICT
  
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Run check script
        run: node check.js
